In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    'id': [1,2,3,4],
    'value': [10, 20, 30, 40],
    'category': ['A', 'B', 'A', 'B']
})

In [4]:
df

   id  value category
0   1     10        A
1   2     20        B
2   3     30        A
3   4     40        B

In [7]:
df['value_square'] = df['value'].apply(lambda x: x ** 2 if x > 20 else x)

In [8]:
df

   id  value category  value_square
0   1     10        A            10
1   2     20        B            20
2   3     30        A           900
3   4     40        B          1600